##############################################################
observation_space: ???
action_space: ???
action_type: cont
frame_stack: 3
action_repeat: 2
device: cuda
seed: 1
use_aug: True # use observation augmentation?
use_irs: False # use intrinsic reward?
# train
num_train_frames: 500000
num_seed_frames: 4000
batch_size: 256
num_workers: 4
pin_memory: true
# test
test_every_frames: 10000
num_test_episodes: 10

##############################################################
encoder:
  _target_: hsuanwu.xploit.encoder.VanillaCnnEncoder
  observation_space: ${observation_space}
  feature_dim: 50

##############################################################
learner:
  _target_: hsuanwu.xploit.learner.ContinuousLearner
  observation_space: ${observation_space}
  action_space: ${action_space}
  device: ${device}
  feature_dim: 50
  hidden_dim: 1024
  lr: 1e-4
  critic_target_tau: 0.01
  num_expl_steps: 2000
  update_every_steps: 2
  stddev_schedule: linear(1.0, 0.1, 100000)
  stddev_clip: 0.3

##############################################################
buffer:
  _target_: hsuanwu.xploit.storage.NStepReplayBuffer
  observation_space: ${observation_space}
  action_space: ${action_space}
  buffer_size: 500000
  n_step: 3
  discount: 0.99

##############################################################
distribution:
  _target_: hsuanwu.xplore.distribution.TruncatedNormal

##############################################################
augmentation:
  _target_: hsuanwu.xplore.augmentation.RandomShift
  pad: 4

##############################################################
reward:
  _target_: hsuanwu.xplore.reward.RE3
  observation_space: ${observation_space}
  action_space: ${action_space}
  action_type: ${action_type}

##############################################################
hydra:
  run:
    dir: ./logs/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  job:
    chdir: true
  # launcher:
  #   timeout_min: 4300
  #   cpus_per_task: 10
  #   gpus_per_node: 1
  #   tasks_per_node: 1
  #   mem_gb: 160
  #   nodes: 1
  #   submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm