seed: 1 
device: cuda                            
use_aug: true                           
use_irs: false                            
num_train_steps: 250000                  
num_init_steps: 2000                     
# test setup
test_every_steps: 50000
num_test_episodes: 10                   

encoder:
  _target_: VanillaCnnEncoder             # encoder name
  feature_dim: 50  

learner:
  _target_: ContinuousLearner             # learner type
  hidden_dim: 1024                        # size of the hidden layers.
  lr: 1e-4                                # learning rate
  critic_target_tau: 0.01                 
  num_expl_steps: 2000
  update_every_steps: 2
  stddev_schedule: linear(1.0, 0.1, 100000)
  stddev_clip: 0.3

buffer:
  _target_: NStepReplayBuffer
  buffer_size: 500000
  batch_size: 256
  pin_memory: true
  num_workers: 4
  n_step: 3
  discount: 0.99
  fetch_every: 1000
  save_snapshot: false

distribution:
  _target_: TruncatedNormal

##############################################################
augmentation:
  _target_: RandomShift
  pad: 4

##############################################################
reward:
  _target_: RE3
  beta: 0.05
  kappa: 0.00001
  latent_dim: 128

##############################################################
hydra:
  run:
    dir: ./logs/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  job:
    chdir: true