site_name: "Hsuanwu"
site_url: https://docs.hsuanwu.dev/
copyright: Copyright &copy; 2023 Bellman Project
theme:
  name: material
  logo: assets/images/icon.svg
  favicon: assets/images/icon.svg
  # custom_dir: docs/theme_override_home/
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

extra_css:
  - assets/stylesheets/extra.css

repo_url: https://github.com/BellmanProject/Hsuanwu
repo_name: BellmanProject/Hsuanwu

extra:
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/BellmanProject/Hsuanwu
    - icon: fontawesome/solid/paper-plane
      link: friedrichyuan19990827@gmail.com
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/hsuanwu/
  
nav:
  - Overview: 
    - Overview: index.md
    - Changelog: changelog.md
    - License: license.md
  - Getting stared:
    - Installation: getting_started.md
  - API Documentation:
    - Overview: overview/api_overview.md
    - xploit:
      - encoder: 
        - base: api/xploit/encoder/base.md
    - xplore:
      - reward:
        - Base: api/xplore/reward/base.md
        - ICM: api/xplore/reward/icm.md
        - RND: api/xplore/reward/rnd.md
        - GIRM: api/xplore/reward/girm.md
        - NGU: api/xplore/reward/ngu.md
        - RIDE: api/xplore/reward/ride.md
        - RE3: api/xplore/reward/re3.md
        - RISE: api/xplore/reward/rise.md
        - REVD: api/xplore/reward/revd.md
      - augmentation:
        - Base: api/xplore/augmentation/base.md
        - RandomCrop: api/xplore/augmentation/random_crop.md
        - RandomShift: api/xplore/augmentation/random_shift.md
      - distribution:
        - Base: api/xplore/distribution/base.md
        - TruncatedNormal: api/xplore/distribution/truncated_normal.md
        - OrnsteinUhlenbeck: api/xplore/distribution/ornstein_uhlenbeck.md
  - Benchmarks: benchmarks.md
