num_actors: 80
num_threads: 4
num_steps: 100
batch_size: 32
baseline_cost: 0.5


learner:
  ent_coef: 0.001
  baseline_coef: 0.5
  discount: 0.99
  max_grad_norm: 40

storage:
  num_steps: 100
  num_storages: 60